### PR TITLE
Factor out diagrams

### PR DESCRIPTION
**Pull request by znmeb**
This has the code to build the diagrams in code and insert them into the HTML and PDF documents. It turns out there's a package `DiagrammeRsvg` that exports a DiagrammeR `html_widget` object to SVG. The format conversions are done by `magick`.

Note that there are new packages required to build the book. I've created a branch on `sqlpetr`, also named `factor-out-diagrams` with those changes.

### CODE REVIEW

**Comment by smithjd** [comment]
I think we should run this first and back it out if necessary.

**Comment by SophieMYang** [comment]
I am not quite sure I am much help here.  Was/am I suppose to recreate the book?  I have issues just running the individual Rmds.  Let me know what you need me to do.  I see that John deleted the branch.

**Comment by smithjd** [comment]
I don't think you need to recompile the book unless you want to delve for the love of sport.

the diagram in `22-drilling-into-db-environment.Rmd` is now working perfectly, as you can see here: https://smithjd.github.io/sql-pet/drilling-into-your-db-environment-22.html

I'm having some trouble, however, with `92-environment_diagram.Rmd`.  Stay tuned.

**Comment by znmeb** [comment]
I'll take a look at it - I want to factor out the diagram pipeline into something repeatable.

**Comment by SophieMYang** [comment]
Who am I to argue with perfection!
    On Tuesday, 23 October 2018, 20:18:18 GMT-7, John David Smith <notifications@github.com> wrote:  
 
 
I don't think you need to recompile the book unless you want to delve for the love of sport.

the diagram in 22-drilling-into-db-environment.Rmd is now working perfectly, as you can see here: https://smithjd.github.io/sql-pet/drilling-into-your-db-environment-22.html

I'm having some trouble, however, with 92-environment_diagram.Rmd. Stay tuned.

**Comment by SophieMYang** [comment]
Ok so maybe it isn't quite perfect yet then.
    On Tuesday, 23 October 2018, 21:05:24 GMT-7, M. Edward (Ed) Borasky <notifications@github.com> wrote:  
 
 
I'll take a look at it - I want to factor out the diagram pipeline into something repeatable.

**Pull request merged**
