### PR TITLE
Database user's password in an untracked file.

### PR DESCRIPTION
**Pull request by jimtyhurst**
These changes are one possible solution to Issue #5 . The database password is kept in an untracked file, so that it will not be committed accidentally to the git repository.

I want people to see what I have in mind. However, I do not think that I should merge it as-is, because it breaks up the flow of introducing PostgreSQL in a container.

I was not sure where to put this block of code. It seems like it should be pulled out to a separate section/chapter on `Security Considerations`. I put it in `04-docker-setup-postgres-connect-with-r.Rmd`, because that is the first place that the `postgres` password is required.

I am open to suggestions for improvement.

### CODE REVIEW

**Comment by znmeb** [comment]
Is `getPass` compatible with Windows, MacOS and Linux? I was looking at `keyring` for this - https://cran.r-project.org/web/packages/keyring/index.html

**Comment by jimtyhurst** [comment]
> Is `getPass` compatible with Windows, MacOS and Linux? I was looking at `keyring` for this - https://cran.r-project.org/web/packages/keyring/index.html

`keyring` accesses the system's credential store. `getPass` is just a UI to prompt for a password. From the [`getPass` documentation](https://cran.r-project.org/package=getPass): 
```
A micro-package for reading "passwords", i.e. reading user input with masking, 
so that the input is not displayed as it is typed. Currently we have support for 
'RStudio', the command line (every OS), and any platform where 'tcltk' is present.
```
So "the command line (every OS)" covers Windows, MacOS and Linux. And I assume most users will be using RStudio, which is included.

Another option that I considered is `.rs.askForPassword`, which displays a mask as you are typing in  a password, but it only works in RStudio. I could not remember if we are assuming that all users will be using RStudio.

**Comment by znmeb** [comment]
Right now, the only secret we have is the `postgres` password. The user would need to enter it before the Docker image was created. I would expect it to be stored securely and have to enter it again frequenty and never see it in cleartext anywhere. If `getPass` can do that, I'd go with it because it's simpler than `keyring`.

**Comment by smithjd** [comment]
@jimtyhurst Do you want to resolve the conflicts with the current `master` or ?  How should we proceed with the password-management issue?

**Pull request merged**
