### PR TITLE
Implementing decisions made on September 15, 2018.

### PR DESCRIPTION
**Pull request by smithjd**

### CODE REVIEW

**Comment by znmeb** [comment]
OK - I added the "new_session: yes" key to `_bookdown.yml`. This is required for the "knit-merge" scheme (one R session per chapter).

However:

1. It takes too long to build the book if we execute the Docker operations while rendering it. I think we need to break the *execution* of them into a separate script. We can leave the code in the book for people to copy and paste / type themselves. Just add `eval=FALSE` to the code chunks.

2. After fixing the duplicate chunk label (issue #71), it still crashes building the book:

```
Quitting from lines 82-98 (05-docker-setup-postgres-with-dvdrental.Rmd) 
Error in connection_create(names(opts), as.vector(opts)) : 
  FATAL:  database "dvdrental" does not exist
Calls: local ... <Anonymous> -> <Anonymous> -> .local -> connection_create
Execution halted
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile 05-docker-setup-postgres-with-dvdrental.Rmd
Calls: <Anonymous> ... render_book -> render_new_session -> Rscript_render
Execution halted

Exited with status 1.
```

**Comment by smithjd** [comment]
I think for different machines we need to adjust the sleep between steps.  When I've seen that kind of error it's due to running out of time.  If you increase the sleep seconds -- double them, say -- it's boring to re-knit the book, but it works.

What about just knitting one chunk at a time?

**Comment by znmeb** [comment]
I think we need a separation of concerns - a book and a package - and we need to package the long-running stuff in a bulletproof script. That's the way Robin Lovelace is building his book on doing GIS in R. The book is in one repo and in another repo he has a package that does some of the heavy lifting. I haven't tried to render his book recently; he may have some long-running things in there, or he may have offloaded them to the package.

**Comment by znmeb** [comment]
P.S.: You shouldn't need sleeps to make a program work; you should be able to test whether the event you're waiting for has happened or not.

**Comment by smithjd** [comment]
I'm pretty sure that I pulled from `master`.  Can we retrieve the changes to those files or can you point to them @jimtyhurst ?

Sorry if I've messed things up!

**Comment by smithjd** [comment]
Hi Jim, are these the changes that you thought had gotten lost? https://github.com/smithjd/sql-pet/pull/62/

**Comment by smithjd** [comment]
There are defects in my method, but I'm going to merge and then include the 2 files that Jim has pointed to.

**Comment by smithjd** [comment]
And I deleted the branch, as Jim has suggested is good practice.

**Comment by jimtyhurst** [comment]
I guess I misinterpreted what would happen when the branch was merged. I could see that a couple of recent files were missing on the branch, but they were present on master. So I assumed they would be deleted when the merge occur. I am happy that they did not get deleted, but I do not have a good explanation of how everything turned out well. In particular, I am not sure why those couple of files did not appear in the branch. My conclusion: No harm, no foul!

**Pull request merged**
