### PR TITLE
Enhanced Ch. 11 "DBI package and SQL"

### PR DESCRIPTION
**Pull request by jimtyhurst**
* Added some explanation around the code.
* Formatting: Added fully-specified package names as prefix to function names.

This chapter is still just an outline, but for the code that was already present, I wanted to provide some text, explaining the significance of the code.

Still to do in a later pull request:
* Write Section 11.4 "Dividing the work between R on your machine and the DBMS".
* Add another section that mentions the other `DBI` functions. `dbSendQuery` is in the current examples. See also:
    +  `dbGetQuery` for interactive use with `SELECT` statements.
    + `dbSendStatement` or `dbExecute` for other statement types.

### CODE REVIEW

**Comment by smithjd** [comment]
I agree with your edits.  Strongly agree that we don't really know what we're talking about regarding "dividing your work between R and SQL" -- yet.  It needs more instrumentation and context.

**Comment by maryannet** [comment]
Jim has good ideas. I recommend writing this section. Have a couple different view points. Mine is do as much as possible in the database.

**Comment by jimtyhurst** [comment]
I think it is a little strong to say:

> we don't really know what we're talking about regarding "dividing your work between R and SQL" -- yet

I think there are a couple variations to discuss:

* When to use `dplyr` and pipes vs `DBI` and SQL.
    This seems like a personal choice, depending on your level of expertise in R data.frames vs SQL.
* When to pull entire tables into a `data.frame` vs perform `SELECT` operations on the dbms (using either `dplyr` or `DBI`.
    This seems like a typical space vs time trade-off, depending on how much data you can fit in your R workspace. I assume that a dbms performs much faster for most operations on a large dataset, but if you are transferring large amounts of data after those operations, then it might be faster to download the data once and then do those operations locally.

I will write a draft for Section 11.4 "Dividing the work between R on your machine and the DBMS" after I review chapters 12 and 13.

**Comment by jimtyhurst** [comment]
@SophieMYang asked:
> What is the 3 digit file number, 100?

File `100-dbi-and-sql.Rmd` is Chapter 11 "[DBI package and SQL](https://smithjd.github.io/sql-pet/chapter-dbi-package-sql.html)".

> dbFetch discussion should be moved to an advanced section, maybe with optimization.

My changes were just clean-up of what was already there. So I will merge these changes and then we can rearrange structure in the next pull request.

> The 120 file can be dropped. It became 130-160.

I am just going with what I see on the `master` branch, which includes a lot of duplication of content in files:

* `110-sql-dplyr-joins.Rmd`
* `120-sql-joins-and-complex-queries.Rmd`
* `130-sql-dplyr-joins-data.Rmd`

but I did _not_ edit any of those files for this pull request. Maybe some group effort is needed to get rid of old or duplicate files that are no longer needed. In general, it is bad etiquette to leave multiple versions of content in the repository with different names. The idea of source control is to have the latest and greatest on the master branch and other versions can be reviewed or revisited in previous commits.

**Comment by SophieMYang** [comment]
Jim - I answered the wrong thread.  I agree on both points.  If you know SQL, you have many different ways of writing statements to get the same results.  The database operations that can be pushed down to the server should be.  Database servers are architected to handle large volumes, lots of memory, indexing, and other optimizations, especially reporting databases.  Clients connecting to a database server are much more restricted in memory and disk space.  All data reduction should also be pushed down to the server.   The extreme example is getting the count of a table.  There is no reason to pull a large table down the wire and then count it.  

Some of this discussion may lead to strategies when working in a database.  Start small, check boundary conditions, defining the driving tables, etc.

**Comment by jimtyhurst** [comment]
I merged my changes to what was already there (closed this pull request), but the comments point out that much more work is needed in this chapter 11. Certainly more needs to be added, but probably some moving of sections to other chapters. I need to get more familiar with the rest of the book before I can make those restructuring changes.

**Pull request merged**
